import type { Metadata } from 'next';

import './globals.css';

import { ConvexAuthNextjsServerProvider } from '@convex-dev/auth/nextjs/server';
import { ConvexClientProvider } from '@/components/convex-client-provider';

import PopoverProvider from '@/components/providers/sidebarContext';
import { JotaiProvider } from '@/components/jotai-provider';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ConvexClientProvider>
            <JotaiProvider>
              <Toaster />
              <PopoverProvider>{children}</PopoverProvider>
            </JotaiProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
